### ISSUE TITLE
AEG Comfort 6000 - Target Heater-Cooler State invalid value / undefined

### ISSUE THREAD

**Issue by hasta85** [tomekkleszcz/homebridge-electrolux-devices#63]
**Describe The Bug:**
Homebridge logs a warning message regarding the Target Heater-Cooler state as it receives the value as undefined.
As far as I can see, there isn't really any issue except the warning message. Haven't tested the device thoroughly yet though.

**To Reproduce:**
Basically default behaviour when adding the device

**Expected behavior:**
According to https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

If you see this message in the log, the plugin attempted to set an invalid value for a certain characteristic. This is just an informative warning message, Homebridge will automatically correct the value to a valid one.

**Logs:**

```
[5/26/2024, 9:09:23 AM] [homebridge-electrolux-devices] This plugin generated a warning from the characteristic 'Current Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.
[5/26/2024, 9:09:23 AM] [homebridge-electrolux-devices] Error: 
    at CurrentHeaterCoolerState.Characteristic.characteristicWarning (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at CurrentHeaterCoolerState.Characteristic.validateUserInput (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2903:14)
    at CurrentHeaterCoolerState.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2405:24)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Plugin Config:**

```
json
        {
            "email": "*reducted*",
            "password": "*reducted*",
            "pollingInterval": 30,
            "carbonDioxideSensorAlarmValue": 1000,
            "vocMolecularWeight": 30.026,
            "platform": "HomebridgeElectroluxDevices",
            "_bridge": {
                "username": "MA:CA:DD:RE:SS",
                "port": 31464
            }
        },
```

**Screenshots:**
![image](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/170851408/ca30f552-73ac-4396-be8d-6364165f7cba)

**Environment:**

* **Plugin Version**: 0.2.0
* **Homebridge Version**: 1.8.2
* **Node.js Version**: 20.12.2
* **NPM Version**: 10.5.0
* **Operating System**: Raspbian: Linux 6.6.28+rpt-rpi-2712 ; Docker version 26.1.3, build b72abbb

**Comment by benjeffreys** [comment]
Just to say - I saw a very similar thing with my new Comfort 6000 as well... this morning. But, it seems to have cleared itself now?

The error I was getting was...

[7/3/2025, 1:24:43 PM] [homebridge-electrolux-devices] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

Now it's stopped and I see the current temperature in the Home tile. Which is great of course :)

**Comment by tomekkleszcz** [comment]
@benjeffreys Great, happy to hear. Let me know if everything's working as it's supposed to. The Electrolux API is not the most reliable, and sometimes it causes some issues.
